spring:
  datasource:
    url: jdbc:h2:file:./student-db
    username: 'sa'
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console:
      path: '/console'
  jpa:
    hibernate:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true